apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
  namespace: gateway
spec:
  selector:
    app: haproxy

  ports:
    - name: http
      port: 80
      targetPort: 8080

  # No GKE cria o Load Balancer externo da POC.
  type: LoadBalancer
